### ISSUE TITLE
[Error.Jade]

### ISSUE THREAD

**Issue by NathanBland** [whiteboards/converse#21]
Image on error page is not sized correctly.

**Comment by NathanBland** [comment]
![tmp_27649-screenshot_2015-12-11-19-12-31123972704](https://cloud.githubusercontent.com/assets/926111/11759643/961c8c0c-a03c-11e5-93c8-0414321e0348.png)

**Comment by keawade** [comment]
Looks better now:

![screenshot_2015-12-12-16-17-19](https://cloud.githubusercontent.com/assets/7308850/11764193/1acc9a0a-a0ec-11e5-9c84-e38630fff8fd.png)
